on:
  push:
    paths:
      - Hydrology.md
      - make-ctv-file.yaml

name: Make CTV file

jobs:
  render:
    name: Make CTV file
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    - name: Convert to ctv
      run: pandoc -w html --wrap=none -o Hydrology.ctv Hydrology.md
    - name: Build XML
      run: Rscript -e 'source("buildxml.R")'
    - name: Install packages and convert to html
      run: Rscript -e 'install.packages("ctv"); ctv::ctv2html("Hydrology.ctv")'
    - name: Make README
      run: pandoc -w gfm --wrap=none -o README.md Hydrology.html
    - name: sed1
      run: |
        sed -i.tmp -e 's|( \[|(\[|g' README.md
        sed -i.tmp -e 's| : |: |g' README.md
    - name: sed3
      run: sed -i.tmp -e 's|../packages/|http://cran.rstudio.com/web/packages/|g' README.md
    - name: sed4
      run: rm *.tmp
    - name: check
      run: Rscript -e 'print(ctv::check_ctv_packages("Hydrology.ctv", repos = "http://cran.rstudio.com/"))'
    - name: check urls
      run: Rscript -e 'source("checkurls.R")'
    - name: Create README.md
      run: pandoc --from=gfm -o README.html README.md
    - name: Commit results
      run: |
        git commit README.md -m 'Re-build README.md'
        git commit Hydrology.ctv -m 'Re-build Hydrology.ctv'
        git commit Hydrology.html -m 'Re-build Hydrology.html'
        git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master
